server:
  port: 8256
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        read-timeout: 5000
        connect-timeout: 5000
spring:
  datasource:
    url: jdbc:mysql://60.205.180.234:3306/fdk_forwarder4?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: fdk
    password: fdksu123456