server:
  port: 8256
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        read-timeout: 5000
        connect-timeout: 5000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: root